#!/usr/bin/env python3
import sys

# This is a script that returns both the reverse complement of 
# DNA sequences in a file.

fasta = {}

with open(sys.argv[1]) as file_one:
	for line in file_one:
		line = line.rstrip()
		if len(line) == 0:
			continue
		if line.startswith(">"):
			active_sequence_name = line[1:]
			if active_sequence_name not in fasta:
				fasta[active_sequence_name] = ''
		else:
			fasta[active_sequence_name] = fasta[active_sequence_name]+line

##print(fasta)
#Will print the data now in a dictionary
###
#{'seq1': 'AAGAGCAGCTCGCGCTAATGTGATAGATGGCGGTAAAGTAAATGTCCTATGGGCCACCAATTATGGTGTATGAGTGAATCTCTGGTCCGAGATTCACTGAGTAACTGCTGTACACAGTAGTAACACGTGGAGATCCCATAAGCTTCACGTGTGGTCCAATAAAACACTCCGTTGGTCAAC', 'seq2': 'GCCACAGAGCCTAGGACCCCAACCTAACCTAACCTAACCTAACCTACAGTTTGATCTTAACCATGAGGCTGAGAAGCGATGTCCTGACCGGCCTGTCCTAACCGCCCTGACCTAACCGGCTTGACCTAACCGCCCTGACCTAACCAGGCTAACCTAACCAAACCGTGAAAAAAGGAATCT', 'seq3': 'ATGAAAGTTACATAAAGACTATTCGATGCATAAATAGTTCAGTTTTGAAAACTTACATTTTGTTAAAGTCAGGTACTTGTGTATAATATCAACTAAAT', 'seq4': 'ATGCTAACCAAAGTTTCAGTTCGGACGTGTCGATGAGCGACGCTCAAAAAGGAAACAACATGCCAAATAGAAACGATCAATTCGGCGATGGAAATCAGAACAACGATCAGTTTGGAAATCAAAATAGAAATAACGGGAACGATCAGTTTAATAACATGATGCAGAATAAAGGGAATAATCAATTTAATCCAGGTAATCAGAACAGAGGT'}
###

#for key in fasta.items():
	#print (key)
#Will print the data as a string. One in each line
###
#('seq1', 'AAGAGCAGCTCGCGCTAATGTGATAGATGGCGGTAAAGTAAATGTCCTATGGGCCACCAATTATGGTGTATGAGTGAATCTCTGGTCCGAGATTCACTGAGTAACTGCTGTACACAGTAGTAACACGTGGAGATCCCATAAGCTTCACGTGTGGTCCAATAAAACACTCCGTTGGTCAAC')
#('seq2', 'GCCACAGAGCCTAGGACCCCAACCTAACCTAACCTAACCTAACCTACAGTTTGATCTTAACCATGAGGCTGAGAAGCGATGTCCTGACCGGCCTGTCCTAACCGCCCTGACCTAACCGGCTTGACCTAACCGCCCTGACCTAACCAGGCTAACCTAACCAAACCGTGAAAAAAGGAATCT')
#('seq3', 'ATGAAAGTTACATAAAGACTATTCGATGCATAAATAGTTCAGTTTTGAAAACTTACATTTTGTTAAAGTCAGGTACTTGTGTATAATATCAACTAAAT')
#('seq4', 'ATGCTAACCAAAGTTTCAGTTCGGACGTGTCGATGAGCGACGCTCAAAAAGGAAACAACATGCCAAATAGAAACGATCAATTCGGCGATGGAAATCAGAACAACGATCAGTTTGGAAATCAAAATAGAAATAACGGGAACGATCAGTTTAATAACATGATGCAGAATAAAGGGAATAATCAATTTAATCCAGGTAATCAGAACAGAGGT')#

#for key in fasta:
	#print(key)
#Will print a different output
###
#seq1
#seq2
#seq3
#seq4

for seq in fasta:	
	sequences = fasta[seq]
	group = key.replace('A','t')
	group = key.replace('T','a')
	key = key.replace('C','g')
	key = key.replace('G','c')
	key = key.upper()
	key = key[::-1]
	
print(key)

#for key,value in fasta:
	#fasta[key] = fasta[key]+"  This is reverse complement  "+sequence


